// <auto-generated />
using System;
using System.Collections.Generic;
using AutoMapperDemoData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapperDemoData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoMapperDemoData.ProductComplex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ComplexProperty<Dictionary<string, object>>("Dimension", "AutoMapperDemoData.ProductComplex.Dimension#Dimension", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Depth")
                                .HasColumnType("decimal(5, 2)");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(5, 2)");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("decimal(5, 2)");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(5, 2)");
                        });

                    b.HasKey("Id");

                    b.ToTable("ProductsComplex");
                });

            modelBuilder.Entity("AutoMapperDemoData.ProductOwned", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductSOwned");
                });

            modelBuilder.Entity("AutoMapperDemoData.ProductOwned", b =>
                {
                    b.OwnsOne("AutoMapperDemoData.Dimension", "Dimension", b1 =>
                        {
                            b1.Property<Guid>("ProductOwnedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Depth")
                                .HasColumnType("decimal(5, 2)");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(5, 2)");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("decimal(5, 2)");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(5, 2)");

                            b1.HasKey("ProductOwnedId");

                            b1.ToTable("ProductSOwned");

                            b1.WithOwner()
                                .HasForeignKey("ProductOwnedId");
                        });

                    b.Navigation("Dimension")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
